version: '3'
services:
   vprodb:
     image: "ozaszhuka/mysql:V1"
     ports:
        - "3306:3306"
     volumes:
        - vprodbdata:/var/lib/mysq
     environment:
        MYSQL_ROOT_PASSWORD: admin123
        MYSQL_DATABASE: db01
   vprocache01:
     image: "ozaszhuka/memcached:V1"
     ports:
        - "11211:11211"
   vpromq01:
     image: "ozaszhuka/rabbitmq:V1"
     ports:
        - "5672:5672"
     environment:
        RABBITMQ_DEFAULT_USER: test
        RABBITMQ_DEFAULT_PASS: test
   vproapp:
     image: "ozaszhuka/tomcat:V1"
     ports:
        - "8087:8080"
     volumes:
        - vproappdata:/usr/local/tomcat/webapps
   vproweb:
     image: "ozaszhuka/nginx:V1"
     ports:
        - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}